### ISSUE TITLE
Error: Could not find or load main class wordcount.core

### ISSUE THREAD

**Issue by liorsbg** [Azure-Samples/hdinsight-python-storm-wordcount#1]
Hi, I'm follwing the instructions for the Clojure topology.
After successfully running locally, creating the uberjar, and scp'ing to the head node,
I run:
`storm jar wordcount-1.0-SNAPSHOT.jar wordcount.core wordcount`
and get: 

```
Running: /usr/lib/jvm/java-7-openjdk-amd64/bin/java -client -Ddaemon.name= -Dstorm.options= -Dstorm.home=/usr/hdp/2.4.2.4-5/storm -Dstorm.log.dir=/var/log/storm -Djava.library.p.
Error: Could not find or load main class wordcount.core
```

What am I missing?

**Comment by Blackmist** [comment]
Hi @liorsbg can you use the following command from the cluster to verify the contents of the jar file?
`jar tf wordcount-0.1.0-SNAPSHOT.jar`
This should return the following:

```
META-INF/MANIFEST.MF
project.clj
clojure/
clojure/tools/
clojure/tools/logging$eval37$fn__38.class
clojure/tools/logging$eval37$fn__43.class
clojure/tools/logging$eval37.class
clojure/tools/logging$eval50$reify__51.class
clojure/tools/logging$eval50.class
wordcount/
wordcount/core$fn__54.class
wordcount/core$loading__4910__auto__.class
wordcount/core$mk_topology.class
wordcount/core$run_local_BANG_.class
wordcount/core$submit_topology_BANG_.class
wordcount/core$_main.class
wordcount/core.class
wordcount/core__init.class
resources/
resources/countbolt.py
resources/sentencespout.py
resources/splitbolt.py
resources/storm.py
wordcount/core.clj
```

If it returns something different (missing the wordcount/core files,) then the file isn't being built correctly or something is happening in the upload process.

I've just tested on an HDInsight cluster (3.4 version,) with no problems, but the path in your error looks like it has a newer version of HDP, so maybe a 3.5 cluster? I'm creating one of those now and will test there once it is running.

**Comment by Blackmist** [comment]
Just a followup: 3.5 cluster works for me as well. Please let me know what results you get from the jar tf wordcount-0.10-SNAPSHOT.jar command.

**Comment by liorsbg** [comment]
Hi @Blackmist thanks for looking into this!

Here's my output for  `jar tf wordcount-0.1.0-SNAPSHOT.jar`:

```
META-INF/MANIFEST.MF
project.clj
wordcount/
wordcount/core$fn__54.class
wordcount/core.class
wordcount/core__init.class
wordcount/core$loading__4910__auto__.class
wordcount/core$_main.class
wordcount/core$run_local_BANG_.class
wordcount/core$mk_topology.class
wordcount/core$submit_topology_BANG_.class
clojure/
clojure/tools/
clojure/tools/logging$eval50.class
clojure/tools/logging$eval50$reify__51.class
clojure/tools/logging$eval37.class
clojure/tools/logging$eval37$fn__43.class
clojure/tools/logging$eval37$fn__38.class
resources/
resources/storm.py
resources/splitbolt.py
resources/countbolt.py
resources/sentencespout.py
wordcount/core.clj

```

**Comment by Blackmist** [comment]
Thanks @liorsbg that looks normal, so not sure what might be the problem. What version of Storm on HDInsight are you using? Also, what platform was the project built on (Windows, Linux, MacOS, etc.)?

Would it be possible for you to share the jar file somewhere and send me a link?

**Comment by liorsbg** [comment]
OK, I must have screwed something up in the short time I was playing around.
I started up a new 3.5 cluster and everything works.

Thanks again I really appreciate it :)

**Comment by Blackmist** [comment]
Thanks for letting me know @liorsbg
